// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epnawompgqqiiiawnneo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwbmF3b21wZ3FxaWlpYXdubmVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDIxMzQsImV4cCI6MjA2MDYxODEzNH0.bxrpmqe4uDUAoDAZ26xy80fiSChL89AWJDTgezmVu5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);